import React,{useMemo,useState}from'react';import{SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView}from'react-native';import{createRun,buildAdaptiveCode}from'../src/engine/worldEngine';import{reduceGame}from'../src/engine/gameEngine';import{simulate}from'../src/engine/simulator';import{answerLocal}from'../src/engine/interrogationEngine';

const stages=['brief','terrain','capture','evidence','board','call','threat','end'] as const;
export default function Home(){
 const[run,setRun]=useState(createRun());const[stage,setStage]=useState(0);const[profile,setProfile]=useState<'dense'|'small'>('dense');
 const route=useMemo(()=>simulate(profile),[profile]);const year=profile==='dense'?'1927':'1874';
 function next(){if(stage===2)setRun(r=>reduceGame(r,{type:'CAPTURE_YEAR',value:year}));setStage(s=>Math.min(stages.length-1,s+1))}
 function reset(){setRun(createRun());setStage(0)}
 const unlocked=run.evidence.filter(e=>e.unlocked);
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}>
 <Text style={s.brand}>CASE</Text><Text style={s.case}>AFFAIRE 001 / 23:17</Text>
 {stage===0&&<><Text style={s.red}>DOSSIER REÇU</Text><Text style={s.hero}>NORA VALEN</Text><Text style={s.copy}>Journaliste • disparue. À 23:17, Nora a programmé un message : « Quelqu’un ment. »</Text><View style={s.row}><Pressable style={[s.pill,profile==='dense'&&s.active]} onPress={()=>setProfile('dense')}><Text style={s.pt}>VILLE DENSE</Text></Pressable><Pressable style={[s.pill,profile==='small'&&s.active]} onPress={()=>setProfile('small')}><Text style={s.pt}>PETITE VILLE</Text></Pressable></View></>}
 {stage===1&&<><Text style={s.red}>WORLD ENGINE</Text><Text style={s.hero}>TON TERRAIN EST PRÊT.</Text>{route.map((r,i)=><View style={s.line} key={r.candidate.id}><Text style={s.num}>0{i+1}</Text><View><Text style={s.white}>{r.candidate.name}</Text><Text style={s.dim}>{r.candidate.distanceM} m • {r.purpose}</Text></View></View>)}</>}
 {stage===2&&<><Text style={s.red}>MISSION 01</Text><Text style={s.hero}>CHERCHE UNE ANNÉE.</Text><Text style={s.copy}>Dans la vraie app, la caméra validera ce que tu trouves. Cette démo simule une découverte propre à ton environnement.</Text><View style={s.scan}><Text style={s.year}>{year}</Text><Text style={s.dim}>ANNÉE DÉTECTÉE</Text></View></>}
 {stage===3&&<><Text style={s.red}>PREUVE DÉBLOQUÉE</Text><Text style={s.hero}>21:53 — LÉO</Text><Text style={s.copy}>Nora a appelé Léo Vasseur pendant 4 min 17.</Text><Text style={s.code}>FICHIER : CALL_{year}.dat</Text></>}
 {stage===4&&<><Text style={s.red}>CARNET</Text><Text style={s.hero}>CE QUE TU SAIS.</Text>{unlocked.map(e=><View style={s.evidence} key={e.id}><Text style={s.white}>{e.title}</Text><Text style={s.dim}>{e.detail}</Text></View>)}<Text style={s.copy}>Hypothèse : Léo cache quelque chose. Preuves insuffisantes pour l’accuser.</Text></>}
 {stage===5&&<><Text style={s.red}>INTERROGATOIRE</Text><Text style={s.hero}>LÉO VASSEUR</Text><Text style={s.quote}>« {answerLocal({suspectId:'leo',asked:[],pressure:0},'Où étiez-vous après ?')} »</Text><Text style={s.dim}>Le moteur autorise l’improvisation de formulation, jamais l’invention des faits.</Text></>}
 {stage===6&&<><Text style={s.red}>INCONNU</Text><Text style={s.hero}>TU PROGRESSES VITE.</Text><View style={s.message}><Text style={s.white}>{year} était une mauvaise idée.</Text></View><Text style={s.copy}>Le nombre n’existe pas dans le scénario : il vient de TA partie.</Text></>}
 {stage===7&&<><Text style={s.red}>CHAPITRE I TERMINÉ</Text><Text style={s.hero}>QUI SAVAIT CE QU’ELLE AVAIT DÉCOUVERT ?</Text><Text style={s.copy}>{unlocked.length} preuve • code adaptatif {buildAdaptiveCode(run)} • parcours {profile==='dense'?'ville dense':'petite ville'}</Text></>}
 </ScrollView><View style={s.bottom}>{stage<7?<Pressable style={s.btn} onPress={next}><Text style={s.bt}>CONTINUER →</Text></Pressable>:<Pressable style={s.btn} onPress={reset}><Text style={s.bt}>REJOUER AUTRE ENVIRONNEMENT</Text></Pressable>}</View></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#080a0c'},wrap:{padding:24,paddingTop:64,paddingBottom:130},brand:{color:'#f3f0e7',fontSize:16,fontWeight:'900',letterSpacing:5},case:{color:'#656d69',fontSize:11,letterSpacing:2,marginTop:8,marginBottom:52},red:{color:'#e14d45',fontSize:12,fontWeight:'900',letterSpacing:2},hero:{color:'#f4f1e8',fontSize:40,lineHeight:43,fontWeight:'900',marginTop:12,letterSpacing:-1},copy:{color:'#adb3af',fontSize:18,lineHeight:28,marginTop:24},row:{flexDirection:'row',gap:8,marginTop:30},pill:{borderWidth:1,borderColor:'#303633',padding:12,borderRadius:3},active:{backgroundColor:'#e14d45',borderColor:'#e14d45'},pt:{color:'#f4f1e8',fontSize:11,fontWeight:'800'},line:{flexDirection:'row',gap:18,borderTopWidth:1,borderTopColor:'#242927',paddingVertical:17,marginTop:12},num:{color:'#e14d45',fontWeight:'900'},white:{color:'#f4f1e8',fontSize:17,fontWeight:'800'},dim:{color:'#747d78',marginTop:5},scan:{borderWidth:1,borderColor:'#414945',padding:35,marginTop:35,alignItems:'center'},year:{color:'#f4f1e8',fontSize:54,fontWeight:'900',letterSpacing:7},code:{color:'#e14d45',marginTop:30,fontFamily:'monospace'},evidence:{borderLeftWidth:2,borderLeftColor:'#e14d45',paddingLeft:15,marginTop:22},quote:{color:'#f4f1e8',fontSize:25,lineHeight:34,marginVertical:35},message:{backgroundColor:'#171b19',padding:22,marginTop:28,borderRadius:4},bottom:{position:'absolute',left:24,right:24,bottom:24},btn:{backgroundColor:'#f4f1e8',padding:18,borderRadius:3},bt:{color:'#080a0c',fontWeight:'900',textAlign:'center',letterSpacing:1}});
