// Generates the recorded character voices with ElevenLabs, once, into assets/voices/.
// The API key is only used here, at build time; it never ships in the app.
//
//   ELEVENLABS_API_KEY=… npx vite-node scripts/generate-voices.ts --list    # voices available to the account
//   ELEVENLABS_API_KEY=… npx vite-node scripts/generate-voices.ts           # generate missing or changed lines
//   … --force                                                              # regenerate everything
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { VOICE_LINES } from '../src/voice/lines';

const API = 'https://api.elevenlabs.io/v1';
const OUT = 'assets/voices';
const CONFIG = 'scripts/voices.config.json';
const key = process.env.ELEVENLABS_API_KEY;
const args = new Set(process.argv.slice(2));

type Config = {
  model: string;
  outputFormat: string;
  settings: Record<string, number | boolean>;
  voices: Record<string, string>;
};

async function main() {
  if (!key) throw new Error('ELEVENLABS_API_KEY manquant (variable d’environnement).');
  const config: Config = JSON.parse(readFileSync(CONFIG, 'utf8'));

  if (args.has('--list')) {
    const res = await fetch(`${API}/voices`, { headers: { 'xi-api-key': key } });
    if (!res.ok) throw new Error(`voices: ${res.status} ${await res.text()}`);
    const { voices } = (await res.json()) as { voices: { voice_id: string; name: string; labels?: Record<string, string> }[] };
    for (const v of voices) console.log(`${v.voice_id}  ${v.name}  ${JSON.stringify(v.labels ?? {})}`);
    return;
  }

  const missing = [...new Set(VOICE_LINES.map((l) => l.speaker))].filter((s) => !config.voices[s]);
  if (missing.length) throw new Error(`Voix non attribuée pour : ${missing.join(', ')} (voir ${CONFIG}, --list).`);

  mkdirSync(OUT, { recursive: true });
  const indexPath = `${OUT}/index.json`;
  const index: Record<string, string> = existsSync(indexPath) ? JSON.parse(readFileSync(indexPath, 'utf8')) : {};

  for (const line of VOICE_LINES) {
    const voice = config.voices[line.speaker];
    const hash = createHash('sha1').update(`${config.model}|${voice}|${JSON.stringify(config.settings)}|${line.text}`).digest('hex').slice(0, 12);
    const file = `${OUT}/${line.id}.mp3`;
    if (!args.has('--force') && index[line.id] === hash && existsSync(file)) continue;

    const res = await fetch(`${API}/text-to-speech/${voice}?output_format=${config.outputFormat}`, {
      method: 'POST',
      headers: { 'xi-api-key': key, 'Content-Type': 'application/json', Accept: 'audio/mpeg' },
      body: JSON.stringify({ text: line.text, model_id: config.model, voice_settings: config.settings }),
    });
    if (!res.ok) throw new Error(`${line.id}: ${res.status} ${await res.text()}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
    index[line.id] = hash;
    console.log(`✓ ${line.id} (${line.speaker})`);
  }

  writeFileSync(indexPath, JSON.stringify(index, null, 2) + '\n');
  const entries = VOICE_LINES.filter((l) => existsSync(`${OUT}/${l.id}.mp3`))
    .map((l) => `  ${l.id}: require('../../${OUT}/${l.id}.mp3'),`)
    .join('\n');
  writeFileSync(
    'src/voice/manifest.ts',
    `// Generated by scripts/generate-voices.ts — do not edit by hand.\n// Maps a voice line id to its recorded clip.\nexport const CLIPS: Record<string, number> = {\n${entries}\n};\n`,
  );
  console.log(`${VOICE_LINES.length} répliques, manifest mis à jour.`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
