// Generated by scripts/generate-voices.mjs — do not edit by hand.
// Maps a voice line id to its recorded clip. Empty until the voices are generated.
export const CLIPS: Record<string, number> = {};
